version: "3.7"

services:

  frontend:
    build: ./frontend
    container_name: deeper-latency-monitor-fe
    env_file: .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - 3000:3000
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: deeper-latency-monitor-be
    env_file: .env
    volumes:
      - ./backend/deeper_latency_monitor_be:/app/src
    ports:
      - 3001:3001
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: deeper-latency-monitor-db
    volumes:
      - ./database/data:/pb_data
    ports:
      - 8090:8090
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
